### PR TITLE
Activity register.xml

### PR DESCRIPTION
**Pull request by scooledge**
Added background color to SAVE button

### CODE REVIEW

**Review by supreti17 — CHANGES_REQUESTED** [review]
The save button didn't work when I ran it on Android Studio. I believe you're missing two lines of code. You have to link saveButton variable to save button in Register.xml layout and then call clicklistener. 

saveButton = (Button) findViewById(R.id.buttonSave);
saveButton.setOnClickListener(this);

It worked for me after I added these two lines of code.

**Comment by scooledge** [comment]
@supreti17 That is very peculiar, I thought I put that put that in earlier. I must have thought I did then made the commit too soon. Thanks! Updating.

**Review by supreti17 — APPROVED** [review]

**Comment by supreti17** [comment]
There's two more small problems. 

1. The save button id is "buttonSave" not "buttonStart".
     saveButton = (Button) findViewById(R.id.buttonSave);

2. saveButton.setOnClickListener(Register.this) on Register.java and startButton.setOnClickListener(GetStarted.this) on GetStarted.java didn't work on mine for some reason. I had to change both to startButton.setOnClickListener(this) and saveButton.setOnClickListener(this) to make it work.

Github says that this branch has confilcts but I was able to run it without any problem. You can merge it after you're done with it.

**Comment by scooledge** [comment]
@supreti17 I am confused how there are merge conflicts in the misc.xml file and the build.gradle?

**Comment by scooledge** [comment]
@supreti17 my Register class file has the following in it:

package com.example.skouchi.citytrax;

import android.content.Intent;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.Button;

public class Register extends AppCompatActivity implements View.OnClickListener {

    private Button saveButton;
    private static final String TAG = "SAVE";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_register);

        saveButton = (Button) findViewById(R.id.buttonSave);
        saveButton.setOnClickListener(Register.this);
    }

    @Override
    public void onClick(View v) {
        try {
            Intent intent = new Intent(this, Details.class);
            startActivity(intent);
        } catch (Exception e) {
            Log.d(TAG, "Save Button Tapped!");
        }
    }
}

**Comment by scooledge** [comment]
@supreti17 the merge conflict looks like it originates from your push:

 <component name="ProjectRootManager" version="2" languageLevel="JDK_1_7" default="true" assert-keyword="true" jdk-15="true" project-jdk-name="1.8" project-jdk-type="JavaSDK">

**Comment by scooledge** [comment]
@supreti17 please give this one more look over! Thanks.

**Comment by supreti17** [comment]
@scooledge Looks good!

**Pull request merged**
